mqtt:
  host: hostname
  username: mqtt
  password: password
  topic_prefix: boneiohome
  ha_discovery:
    enabled: yes

oled:

lm75:
  - id: temp
    address: 0x48

event: !include event.yaml
binary_sensor: !include binary_sensor.yaml

output: !include output32x5A.yaml

boneio:
  name: "boneIO Black 32x10A"
  version: 0.8
  device_type: "32x10A"
  

# adc: !include adc.yaml Uncomment only if needed.
