class Chip:
    def _check_closed(self): ...
    def close(self): ...
    def get_info(self): ...
    def line_offset_from_id(self): ...
    def _get_line_info(self): ...
    def get_line_info(self): ...
    def watch_line_info(self): ...
    def unwatch_line_info(self): ...
    def wait_info_event(self): ...
    def read_info_event(self): ...
    def _resolve_config_keys_to_offsets(self): ...
    def request_lines(self): ...
    def fileno(self): ...
    def path(self): ...
    def fd(self): ...
